spring:
  profiles: default
  data.mongodb:
    uri: mongodb+srv://react:${MONGO_PEC_PASS}@cluster0.ro2ul.gcp.mongodb.net/pec?retryWrites=true&w=majority;

adminUser:
  email: admin@pec.com.br
  password: admin